export const ROLES = {
  EMPLOYEE: 'ROLE_EMPLOYEE',
  HR_ADMIN: 'ROLE_HR_ADMIN'
};

export const ATTENDANCE_STATUS = {
  PRESENT: 'PRESENT',
  ABSENT: 'ABSENT',
  HALF_DAY: 'HALF_DAY',
  LEAVE: 'LEAVE'
};

export const LEAVE_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  WITHDRAWN: 'WITHDRAWN',
  RECALLED: 'RECALLED',
  CANCELLED: 'CANCELLED'
};

export const LEAVE_TYPE = {
  PAID: 'PAID',
  SICK: 'SICK',
  UNPAID: 'UNPAID'
};

export const EARLY_RETURN_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED'
};

export const NOTIFICATION_TYPE = {
  LEAVE: 'LEAVE',
  ATTENDANCE: 'ATTENDANCE',
  PAYROLL: 'PAYROLL',
  PROFILE: 'PROFILE',
  SYSTEM: 'SYSTEM'
};
